CHAPTER :- 5........................ NUMPY

NUMPY:::--- NumPy is a Python library used for working with arrays.

In [2]:
import numpy as np
distance = [50,60,40]
speed = [40,30,20]
dis = np.array(distance)
sp = np.array(speed)
time = dis/sp
print (time)

ModuleNotFoundError: No module named 'numpy'

NUMPY ARRAY ATTRIBUTEA:::--

(ndim) :- no. of dimensons , 
(shape) :- size of each dimension ,
(size) :-  total size of dimension

In [ ]:
import numpy as np
distance = [50,60,40]
speed = [40,30,20]
dis = np.array(distance)
sp = np.array(speed)
time = dis/sp
print (time)
print("no.of dimension:-", time.ndim)
print("no.of  each dimension:-", time.shape)
print("no.of  total dimension:- ", time.size)



[1.25 2.   2.  ]
no.of dimension:- 1
no.of  each dimension:- (3,)
no.of  total dimension:-  3


In [ ]:
# randint():-  it is used for return random integer 
# numpy arrange():- it is use for arrange the elemnt of the array
#  np.random():- it is use for choose random number in array


# np.arange()

a = [10,20,30,40,50,60,70,80,90,100]
a = np.arange(0,100,5)

# np.random

print("the finall value of a is:-\n",a)
print("second element of the array:-\n",a[1])
print("last element of the array:-\n",a[-1])
print("first element of the array:-\n",a[0])


the finall value of a is:-
 [ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
second element of the array:-
 5
last element of the array:-
 95
first element of the array:-
 0


In [ ]:
#  ARRAY CONCATENATION:-they have three methods np.concatenate(), np.vstack(), np.hstack().

# np. concatenate()

x = np.array([12,33,45,67])
y = np.array([45,66,78,90])
np.concatenate([x,y])

array([12, 33, 45, 67, 45, 66, 78, 90])

In [ ]:
# np.vstack()

y = np.array([45,66,78,90])
grid= np.array([[12,22,33,44],
             [34,45,67,89]])
np.vstack([y,grid])


array([[45, 66, 78, 90],
       [12, 22, 33, 44],
       [34, 45, 67, 89]])

In [ ]:
# np.hstack()

grid= np.array([[12,22,33,44],
             [34,45,67,89]])
y= np.array([[12],
             [34]])
np.hstack([grid,y])

array([[12, 22, 33, 44, 12],
       [34, 45, 67, 89, 34]])

CHAPTER :- 6..............PANDAS AND DATAFRAME...........

In [ ]:
# in pandas they have two main data structure 

# 1. SERIES:- A Pandas Series is like a column in a table.It is a one-dimensional array holding data of any type.

# 2. DATAFRAME:- A Pandas DataFrame is a 2 dimensional data structure, like a 2 dimensional array, or a table with rows and columns.

import pandas as pd
import numpy as np

x = pd.Series()
print("the value of empty series is",x)

y = pd.Series([10,20,33,45,6,6767,7686])
print(" the value of y is :- \n",y)


y = pd.Series([10,20,33,45,6,6767,7686] , ['a','b','c','d','e','f','g'])

# Data manipulation


print(" the value of y is  :- \n", y)
print(" adding 5 number in y:- \n " , y+5)
print(" greater then 30 :- \n" , y > 30)

the value of empty series is Series([], dtype: float64)
 the value of y is :- 
 0      10
1      20
2      33
3      45
4       6
5    6767
6    7686
dtype: int64
 the value of y is  :- 
 a      10
b      20
c      33
d      45
e       6
f    6767
g    7686
dtype: int64
 adding 5 number in y:- 
  a      15
b      25
c      38
d      50
e      11
f    6772
g    7691
dtype: int64
 greater then 30 :- 
 a    False
b    False
c     True
d     True
e    False
f     True
g     True
dtype: bool


/tmp/ipykernel_5130/1864039395.py:10: FutureWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  x = pd.Series()


In [ ]:
import pandas as pd
a= pd.Series({'rishi' : 1  , 'raj' : 2 , 'singh' : 3 , 'rajput' : 4})
print("the value of a is :- \n " ,a )
# pd.Series(a)


the value of a is :- 
  rishi     1
raj       2
singh     3
rajput    4
dtype: int64


In [ ]:
import pandas as pd
import numpy as np
Series = pd.Series([10,30,40,50] , index = ['a','b','c','d'])
print(Series)
# WE WILL USE THE SERRIES IN NUMPY AND PANDAS IS I THIS WAY 
Series['b']
print(" adding the number in series :\n" , Series+100)
print("filter the series which is greater then 25:\n",Series[Series>25])
# WE WILL FIND THE SQUARE IN PANDAS BY USING "sqrt" FUCNTION 
print("the square root of series is :-\n" ,np.sqrt(Series))

a    10
b    30
c    40
d    50
dtype: int64
 adding the number in series :
 a    110
b    130
c    140
d    150
dtype: int64
filter the series which is greater then 25:
 b    30
c    40
d    50
dtype: int64
the square root of series is :-
 a    3.162278
b    5.477226
c    6.324555
d    7.071068
dtype: float64


In [ ]:
import pandas as pd
data = [['Rishi','10','2002'],['Manavi','12','2003'],['Aman','30','2004'],['Nainisha','19','2003']]
dt = pd.DataFrame(data,columns=['Name','Age','Year'])
dt

Name Age  Year
0     Rishi  10  2002
1    Manavi  12  2003
2      Aman  30  2004
3  Nainisha  19  2003

In [ ]:
import pandas as pd
data = [['Rishi','10','2002'],['Manavi','12','2003'],['Aman','30','2004'],['Nainisha','19','2003']]
dt = pd.DataFrame(data,columns=['Name','Age','Year'])
dt['Name']

0       Rishi
1      Manavi
2        Aman
3    Nainisha
Name: Name, dtype: object

In [ ]:
import pandas as pd
data = [['Rishi','10','2002'],['Manavi','12','2003'],['Aman','30','2004'],['Nainisha','19','2003']]
dt = pd.DataFrame(data,columns=['Name','Age','Year'])
dt['Age']

0    10
1    12
2    30
3    19
Name: Age, dtype: object

In [ ]:
import pandas as pd
data = [['Rishi','10','2002'],['Manavi','12','2003'],['Aman','30','2004'],['Nainisha','19','2003']]
dt = pd.DataFrame(data,columns=['Name','Age','Year'])
dt['Year']
dt

Name Age  Year
0     Rishi  10  2002
1    Manavi  12  2003
2      Aman  30  2004
3  Nainisha  19  2003

In [ ]:
# import pandas as pd
# data = [['Rishi','10','2002'],['Manavi','12','2003'],['Aman','30','2004'],['Nainisha','19','2003']]
# dt = pd.DataFrame(data,columns=['Name','Age','Year'])
print("original dataframe:\n",dt)
del dt['Year']
print("original dataframe:\n",dt)
del dt['Age']
print("original dataframe:\n",dt)
del dt['Name']
print("original dataframe:\n",dt)

original dataframe:
        Name Age  Year
0     Rishi  10  2002
1    Manavi  12  2003
2      Aman  30  2004
3  Nainisha  19  2003
original dataframe:
        Name Age
0     Rishi  10
1    Manavi  12
2      Aman  30
3  Nainisha  19
original dataframe:
        Name
0     Rishi
1    Manavi
2      Aman
3  Nainisha
original dataframe:
 Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]


.loc() :-  in loc() method we have to pass the name of the row/column which we want to select.

.iloc():-  in iloc() method we have to pass an integer index in the method to select a specific row/column. 


<!-- The Pandas loc indexer can be used with DataFrames for two different use cases:

a.) Selecting rows by label/index
b.) Selecting rows with a boolean / conditional lookup -->


In [ ]:
import pandas as pd
data = pd.DataFrame({'share':[183, 259 , 424 , 4365 ,473,789,1234,894],
                    'company':['APPLE', 'TESLA','SAMSUNG','TATA','EURUSD','XURUSD','ITC','SONATA'],
                    'ticker':['APPL','TXL','SMS','TATA','EU','XU','IC','SNT']})
data

share  company ticker
0    183    APPLE   APPL
1    259    TESLA    TXL
2    424  SAMSUNG    SMS
3   4365     TATA   TATA
4    473   EURUSD     EU
5    789   XURUSD     XU
6   1234      ITC     IC
7    894   SONATA    SNT

In [ ]:
print(data.loc[4]['share']) #....{IN THIS WE WILL USE .LOC[] METHODS AND IS CALL  ONLY ROWS }
print(data.loc[4][2]) #.....{IN THIS WE WILL USE .ILOC[]  METHODS AND IT CALL COLUMNS ONLY}

473
EU


In [ ]:
# data.head()  is use for inspect top 5 rows in dataframe
# data.tail()  is use for inspect below 5 rows in datafream

print("top rows in our chart is :\n" ,data.head())

print("below rows in our chart is:\n",data.tail())



top rows in our chart is :
    share  company ticker
0    183    APPLE   APPL
1    259    TESLA    TXL
2    424  SAMSUNG    SMS
3   4365     TATA   TATA
4    473   EURUSD     EU
below rows in our chart is:
    share company ticker
3   4365    TATA   TATA
4    473  EURUSD     EU
5    789  XURUSD     XU
6   1234     ITC     IC
7    894  SONATA    SNT


In [ ]:
# dtypes() is use for check for each columns
data.dtypes

# .describe() is use for statistics
data.describe()

# .info() is use for  chack information of your data including column data type and non-null valuse and how much memory will used
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   share    8 non-null      int64 
 1   company  8 non-null      object
 2   ticker   8 non-null      object
dtypes: int64(1), object(2)
memory usage: 324.0+ bytes
